import Head from 'next/head';

import styles from './Home.module.scss';

const Home = () => {
  return <div className={ styles.container }>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={ styles.main }>
      <h1 className={ styles.title }>
        Welcome to <a href="https://nextjs.org" target="_blank" rel="noreferrer">Next.js!</a>
      </h1>

      <a href="https://github.com/berkinanik/" className={ styles.link } target="_blank" rel="noreferrer">
        github.com/berkinanik
      </a>

      <p className={ styles.description }>
        This is a custom starter template using{ ' ' }
        <code className={ styles.code }>js</code>with<code className={ styles.code }>npm</code><br/>
        <code className={ styles.code }>es6+ syntax</code>, <code className={ styles.code }>functional compenents</code>and<code className={ styles.code }>sass (scss)</code><br/>
        custom<code className={ styles.code }>eslint</code>with{ ' ' }
        <code className={ styles.code }>next</code> / <code className={ styles.code }>react</code> / <code className={ styles.code }>hooks</code> plugins and more<br/>
        custom<code className={ styles.code }>babel</code>and<code className={ styles.code }>jsconfig</code> for path aliasing<br/>
        basic layout with <code className={ styles.code }>Navbar</code> <code className={ styles.code }>Wrapper</code> <code className={ styles.code }>Footer</code> and <code className={ styles.code }>sass mixins</code>
      </p>

      <p className={ styles.description }>
        Get started by clicking{ ' ' }
        <code className={ styles.code }>Code</code> or <code className={ styles.code }>Use this template</code> on GitHub
      </p>

      <div className={ styles.grid }>
        <a href="https://nextjs.org/docs" className={ styles.card } target="_blank" rel="noreferrer">
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a href="https://nextjs.org/learn" className={ styles.card } target="_blank" rel="noreferrer">
          <h2>Learn &rarr;</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>

        <a
          href="https://github.com/vercel/next.js/tree/canary/examples"
          className={ styles.card } target="_blank" rel="noreferrer"
        >
          <h2>Examples &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={ styles.card } target="_blank" rel="noreferrer"
        >
          <h2>Deploy &rarr;</h2>
          <p>
            Instantly deploy your Next.js site to a public URL with Vercel.
          </p>
        </a>
      </div>
    </main>
  </div>;
};

export default Home;
